config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = params[:query] ? Flat.all : Flat.where("name LIKE '%#{params[:query]}%'")
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(
      :name,
      :address,
      :description,
      :price_per_night,
      :number_of_guests
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :description %>
<%= f.input :price_per_night, inner_html: { min: 0 } %>
<%= f.input :number_of_guests, inner_html: { min: 0 } %>
<%= f.input :picture_url %>
<%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/flats/edit.html.erb
<h1><%= @flat.name %></h1>

<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container">

  <h1>All our flats (<%= @flats.length %>)</h1>

  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-xs-4">

      <div class="card">
        <div class="card-image" style="background-image: url('<%= flat.picture_url %>')"></div>
        <div class="card-body">
          <div class="card-title">
            <h3><%= flat.name %></h3>
          </div>
          <p><%= flat.address %></p>
          <div class="flex">
            <span class="glyphicon glyphicon-user"></span>
            <span><%= flat.number_of_guests %></span>
            <span class="glyphicon glyphicon-euro"></span>
            <span><%= flat.price_per_night %></span>
          </div>
        </div>
        <div class="card-links">
          <%= link_to 'More info', flat_path(flat), class: 'text-info' %>
          <%= link_to 'Edit', edit_flat_path(flat), class: 'text-warning' %>
          <%= link_to 'Remove', flat_path(flat), class: 'text-danger', method: 'delete', data: { confirm: 'Are you sure ?'} %>
        </div>
      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Rent your flat</h1>

<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<div class="banner" style="background-image: url('<%= @flat.picture_url %>"></div>

<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <div class="show-card">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="show-card">
        <h4>Book this place!</h4>
        <form action="#">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2018" aria-describedby="basic-addon1">
          </div>
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2018" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success">
        </form>
      </div>
      <div class="show-card">
        <h3>Details</h3>
          <div class="flex">
            <span class="glyphicon glyphicon-user"></span>
            <span><%= @flat.number_of_guests %></span>
            <span class="glyphicon glyphicon-euro"></span>
            <span><%= @flat.price_per_night %></span>
          </div>
      </div>
      <div class="show-card">
        <span>Share</span>
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span class="glyphicon glyphicon-heart-empty"></span>
        <span class="glyphicon glyphicon-link"></span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Simple Airbnb', flats_path, class: 'navbar-brand' %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
      <div class="nav navbar-nav navbar-right">
        <form action="<%= flats_path %>" class="form-inline">
          <div class="form-group">
            <input type="text" name="query" class="form-control">
            <input type="submit" value="Search" class="form-control btn btn-success" placeholder="<%= params[:query] %>">
          </div>
          <%= link_to 'New Flat', new_flat_path, class: 'btn btn-info' %>
        </form>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>